blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/bitbitdown/mini-create-vite/discussions
    about: æé—®ã€åˆ†äº«æƒ³æ³•å’Œè®¨è®º
  - name: ğŸ“– æ–‡æ¡£
    url: https://github.com/bitbitdown/mini-create-vite#readme
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£å’Œä½¿ç”¨æŒ‡å—
